### ISSUE TITLE
Accept config file as another option to inject configs

### ISSUE THREAD

**Issue by encX** [codeleague/codecoach#103]
### Idea
We have command `codecoach --<config1>=<value1> --<config2>=<value2>` to execute CodeCoach.
Would be nice if we also have `codecoach --config=<configFilePath>` to read from.

And config file could be formatted like
```yaml
repo:
  url: https://github.com/codeleague/codecoach
  pr: 40
  token: 123qwe123qwe123qwe123
buildLogFiles:
- type: tslint
  file: /path/to/log.json
  cwd: /current/dir/of/lint/output
- type: msbuild
  file: /path/to/output/log
  cwd: /path/of/cwd
output: /path/to/codecoach/output.json
```
maybe ?
- also read stdin with yaml/json format too ?
- default config filename like `.codecoach` ? So users can just `codecoach`
